# Generated by Django 3.1.3 on 2020-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=False, upload_to='picture'),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='vishnu', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
