# Generated by Django 3.1.3 on 2020-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_auto_20201217_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('day', models.DateField()),
                ('image', models.ImageField(default=False, upload_to='picture')),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
