# Generated by Django 3.1.3 on 2020-12-22 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day',
            field=models.DateField(default=datetime.date(2020, 12, 22)),
        ),
    ]
